version: '3'

services:

  supertokens:
    container_name: "open-gram-supertokens"
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    ports:
      - 3567:3567
    env_file: .env
    restart: unless-stopped

  postgres:
    container_name: "open-gram-postgres"
    image: postgres:14.0-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  open-gram-mongo:
      container_name: "open-gram-mongo"
      image: mongo:4.0.23-xenial
      hostname: open-gram-mongo
      ports:
          - 27017:27017
      volumes:
          - ./mongo:/data/db
      env_file: .env
      restart: unless-stopped

  api-server:
    container_name: "open-gram-api-server"
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
      - ./prisma:/prisma
    ports:
      - 4000:4000
    env_file: .env
    command: nodemon bin/www
    restart: unless-stopped

  web-server:
      container_name: "open-gram-web"
      build:
          context: ./web
      volumes:
          - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8010:80
      restart: unless-stopped
