version: '3'

services:

  supertokens:
    container_name: "open-gram-supertokens"
    image: registry.supertokens.io/supertokens/supertokens-mongodb
    ports:
      - 3567:3567
    env_file: .env

  api-server:
    container_name: "open-gram-api-server"
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 4000:4000
    env_file: .env

  web-server:
      container_name: "open-gram-web"
      build:
          context: ./web
      volumes:
          - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8010:80
